### ISSUE TITLE
Add DAO fees for each published collection

### ISSUE THREAD

**Issue by fzavalia** [decentraland/collections-graph#49]
Keep in mind that prices in the graph will be in USD after we start using RaritiesWithOracle.

This means that for any kind of tracking, those USD have to be converted to MANA at the rate of the block the publish is made.

**Comment by ef3n9r98** [comment]
Hi @juanmahidalgo, if this is still an issue, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/
).


Thanks!

**Comment by juanmahidalgo** [comment]
hey @ef3n9r98! This has been already resolved by us, thanks for showing interest in resolving it!

**Comment by juanmahidalgo** [comment]
@ef3n9r98 if you are still interested in contributing to Decentraland projects, please feel free to pick any of the issues that are unassigned and marked with the tag `good first issue`!
